$schema: "../schema/config.json"

issuers:
  chickens:
    scopes:
      - openid
    clients:
      - confidential:
          id: client-id
          secret: client-secret
      - public:
          id: frontend
          redirectUrls:
            - http://localhost
