$schema: "../schema/config.json"

issuers:
  - name: chickens
    clients:
      - confidential:
          id: client-id
          secret: client-secret
      - public:
          id: frontend
          redirectUrls:
            - http://localhost
            - exact:
                url: http://localhost
                ignoreLocalhostPort: true
